/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign In */
        post: operations["sign_in_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Signup */
        post: operations["verify_signup_auth_verify_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/database/migrate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Migrate */
        post: operations["migrate_database_migrate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/my-venues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Venues */
        get: operations["get_my_venues_profile_my_venues_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/venues/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Venue */
        post: operations["create_venue_venues__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/venues/{venue_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Venue By Id */
        delete: operations["delete_venue_by_id_venues__venue_id__delete"];
        options?: never;
        head?: never;
        /** Patch Venue */
        patch: operations["patch_venue_venues__venue_id__patch"];
        trace?: never;
    };
    "/venues/p/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Venue By Slug */
        get: operations["get_venue_by_slug_venues_p__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiResponse */
        ApiResponse: {
            /** Success */
            success: boolean;
            /**
             * Data
             * @default []
             */
            data: components["schemas"]["VenueRead"][];
            /** Total */
            total: number;
        };
        /** CategoryRead */
        CategoryRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Menu Id
             * Format: uuid
             */
            menu_id: string;
            /** Name */
            name: string;
            /** Desc */
            desc?: string | null;
            /** Image */
            image?: string | null;
            /** Items */
            items?: components["schemas"]["ItemRead"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ItemRead */
        ItemRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Category Id
             * Format: uuid
             */
            category_id: string;
            /** Name */
            name: string;
            /** Desc */
            desc?: string | null;
            /** Image */
            image?: string | null;
            /** Price */
            price?: string | null;
            /** Weight G */
            weight_g?: number | null;
        };
        /** Login */
        Login: {
            /**
             * Email
             * Format: email
             * @default nazar.konechniy2@gmail.com
             */
            email: string;
            /**
             * Password
             * @default nazar.konechniy2@gmail.com
             */
            password: string;
        };
        /** MenuRead */
        MenuRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Venue Id
             * Format: uuid
             */
            venue_id: string;
            /** Name */
            name: string;
            /** Categories */
            categories?: components["schemas"]["CategoryRead"][];
        };
        /** Register */
        Register: {
            /**
             * Name
             * @default Nazarii
             */
            name: string;
            /**
             * Email
             * Format: email
             * @default nazar.konechniy2@gmail.com
             */
            email: string;
            /**
             * Password
             * @default nazar.konechniy2@gmail.com
             */
            password: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VenueBase */
        VenueBase: {
            /**
             * Name
             * @default Jopa Caffe
             */
            name: string;
            /** Desc */
            desc?: string | null;
            /**
             * Phone
             * @default 353079644297
             */
            phone: string | null;
            /**
             * Wifipassword
             * @default strongPassword
             */
            wifiPassword: string | null;
            /**
             * Address
             * @default 70A Hillcreast Park
             */
            address: string | null;
            /** Google Maps Link */
            google_maps_link?: string | null;
            /** Inst Link */
            inst_link?: string | null;
            /** Facebook Link */
            facebook_link?: string | null;
            /** Tiktok Link */
            tiktok_link?: string | null;
            /**
             * Max Tables
             * @default 20
             */
            max_tables: number | null;
            /**
             * Currency
             * @default USD
             */
            currency: string;
            /**
             * Language
             * @default English
             */
            language: string;
            /**
             * Logo
             * @default default.png
             */
            logo: string;
            /**
             * Background
             * @default defaultBG.png
             */
            background: string;
        };
        /** VenueCreateResponse */
        VenueCreateResponse: {
            venue: components["schemas"]["VenueRead"];
            menu: components["schemas"]["MenuRead"];
            /** Categories */
            categories: components["schemas"]["CategoryRead"][];
            /** Items */
            items: components["schemas"]["ItemRead"][];
        };
        /** VenueRead */
        VenueRead: {
            /**
             * Name
             * @default Jopa Caffe
             */
            name: string;
            /** Desc */
            desc?: string | null;
            /**
             * Phone
             * @default 353079644297
             */
            phone: string | null;
            /**
             * Wifipassword
             * @default strongPassword
             */
            wifiPassword: string | null;
            /**
             * Address
             * @default 70A Hillcreast Park
             */
            address: string | null;
            /** Google Maps Link */
            google_maps_link?: string | null;
            /** Inst Link */
            inst_link?: string | null;
            /** Facebook Link */
            facebook_link?: string | null;
            /** Tiktok Link */
            tiktok_link?: string | null;
            /**
             * Max Tables
             * @default 20
             */
            max_tables: number | null;
            /**
             * Currency
             * @default USD
             */
            currency: string;
            /**
             * Language
             * @default English
             */
            language: string;
            /**
             * Logo
             * @default default.png
             */
            logo: string;
            /**
             * Background
             * @default defaultBG.png
             */
            background: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /**
             * Owner Id
             * Format: uuid
             */
            owner_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Menus */
            menus?: components["schemas"]["MenuRead"][];
        };
        /** VenueUpdate */
        VenueUpdate: {
            /** Name */
            name?: string | null;
            /** Phone */
            phone?: string | null;
            /** Wifipassword */
            wifiPassword?: string | null;
            /** Desc */
            desc?: string | null;
            /** Address */
            address?: string | null;
            /** Google Maps Link */
            google_maps_link?: string | null;
            /** Inst Link */
            inst_link?: string | null;
            /** Facebook Link */
            facebook_link?: string | null;
            /** Tiktok Link */
            tiktok_link?: string | null;
            /** Max Tables */
            max_tables?: number | null;
            /** Currency */
            currency?: string | null;
            /** Language */
            language?: string | null;
            /** Logo */
            logo?: string | null;
            /** Background */
            background?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Register"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sign_in_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Login"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_signup_auth_verify_signup_post: {
        parameters: {
            query: {
                email: string;
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    migrate_database_migrate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_my_venues_profile_my_venues_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
        };
    };
    create_venue_venues__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VenueBase"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VenueCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_venue_by_id_venues__venue_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                venue_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_venue_venues__venue_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                venue_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VenueUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VenueRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_venue_by_slug_venues_p__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
